# https://www.baeldung.com/spring-boot-postgresql-docker
# to run the application, run:
# docker-compose up

version: "3"
services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    container_name: library-app
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/library
      - SPRING_DATASOURCE_USERNAME=usrnm
      - SPRING_DATASOURCE_PASSWORD=psswrd
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: usrnm
      POSTGRES_PASSWORD: psswrd
    ports:
      - "5432:5432"